#!/bin/bash

function readFile {
    ls $1 | dmenu -i -l 20 -p "open:"
}

path=$(pwd)

while [[ -d $path ]]; do
    file=$(readFile $path)
    if [[ -z $file ]]; then
        exit 0
    fi
    path="${path}/${file}"
done

xdg-open $path
