#!/bin/bash

tags_root=$(git rev-parse --show-toplevel)

if [[ -z $tags_root ]]; then
    exit 1
fi

hs_files=$(find $tags_root -not -path '*/\.*' -not -path 'dist' -iname '*.hs' | tr "\n" " ")

fast-tags -o ${tags_root}/tags --no-module-tags --nomerge $hs_files
