#!/bin/bash

tags_root=$(git rev-parse --show-toplevel)

if [[ -z $tags_root ]]; then
    tags_root=$(pwd)
    echo "Can't find git root, using ${tags_root} as tag root"
fi

hs_files=$(find $tags_root -not -path '*/\.*' -not -path 'dist' -iname '*.hs' | tr "\n" " ")

fast-tags -o ${tags_root}/tags --no-module-tags --nomerge $hs_files
