#!/bin/sh

case "$1" in
    lock)
        swaylock --color=00000000
        ;;
    logout)
        swaymsg exit
        ;;
    suspend)
        swaylock --color=000000 && systemctl suspend
        ;;
    hibernate)
        swaylock --color=000000 && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
